version: '3'

services:
  swagger-editor:
    image: swaggerapi/swagger-editor
    networks:
      - swaggernet
    container_name: "swagger-editor"
    ports:
      - "8001:8080"

  swagger-ui:
    image: swaggerapi/swagger-ui
    networks:
      - swaggernet
    container_name: "swagger-ui"
    ports:
      - "8002:8080"
    volumes:
      - ./swagger-document/openapi.yaml:/openapi.yaml
    environment:
      SWAGGER_JSON: /openapi.yaml
      # API_URL: ""

  swagger-api:
    image: danielgtaylor/apisprout
    networks:
      - swaggernet
    container_name: "swagger-api"
    ports:
      - "8003:8000"
    volumes:
      - ./swagger-document/openapi.yaml:/openapi.yaml
    command: /openapi.yaml

  sonarqube-db:
    image: postgres:9.6
    container_name: 'sonarqube-db'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=sonar
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - /var/lib/postgresql/data

  sonarqube:
    image: sonarqube
    depends_on:
      - sonarqube-db
    container_name: 'sonarqube'
    ports:
      - "9000:9000"
    environment:
      - sonar.jdbc.url=jdbc:postgresql://sonarqube-db:5432/sonar
    volumes:
      - /opt/sonarqube/conf
      - /opt/sonarqube/data
      - /opt/sonarqube/extensions

  pokemon-db:
    image: postgres:9.6
    container_name: 'pokemon-db'
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=pokemon
      - POSTGRES_USER=pokemon
      - POSTGRES_PASSWORD=pokemon
    volumes:
      - /var/lib/postgresql/data

  pokemon-api:
    tty: true
    build:
      context: ../pokemon-api
      dockerfile: Dev.Dockerfile
    depends_on:
      - pokemon-db
      - sonarqube-db
      - sonarqube
    container_name: 'pokemon-api'
    volumes:
      - ../pokemon-api/:/usr/app/
      - /usr/app/node_modules
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
      PORT: '80'
      DB_CONFIG: |
        {
          "host": "host.docker.internal",
          "database": "pokemon",
          "username": "pokemon",
          "password": "pokemon",
          "port": "5433"
        }
    ports:
      - '3001:80'
      - '9001:9001'
    entrypoint: './scripts/dev.sh'

  pokemon-client:
    tty: true
    build:
      context: ../pokemon-client
      dockerfile: Dev.Dockerfile
    volumes:
      - ../pokemon-client/:/usr/app/
      - /usr/app/node_modules
    environment:
      NODE_ENV: development
      API_BASE_URL: 'http://localhost:3001/'
    ports:
      - '5000:5000'
    entrypoint: ./scripts/dev.sh

networks:
  swaggernet:
    driver: bridge
