version: '3'

services:
  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: "swagger-editor"
    ports:
      - "8001:8080"

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    depends_on:
      - swagger-nginx
    ports:
      - "8002:8080"
    volumes:
      - ../pokemon-api/swagger/openapi.yaml:/openapi.yaml
    environment:
      SWAGGER_JSON: /openapi.yaml
      # API_URL: ""

  swagger-nginx:
    image: nginx:mainline-alpine
    container_name: "swagger-nginx"
    depends_on:
      - pokemon-api
    ports:
      - "8003:8081"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      swagger_link:
        aliases:
          - local.swagger.api

  sonarqube-db:
    image: postgres:9.6
    container_name: 'sonarqube-db'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=sonar
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - TZ=Japan
    volumes:
      - /var/lib/postgresql/data

  sonarqube:
    image: sonarqube:7.1
    depends_on:
      - sonarqube-db
    container_name: 'sonarqube'
    ports:
      - "9000:9000"
    environment:
      - sonar.jdbc.url=jdbc:postgresql://sonarqube-db:5432/sonar
    volumes:
      - /opt/sonarqube/conf
      - /opt/sonarqube/data
      - /opt/sonarqube/extensions

  pokemon-db:
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pokemon
      MYSQL_USER: pokemon
      MYSQL_PASSWORD: pokemon
    ports:
      - 3307:3306

  pokemon-api:
    networks:
      swagger_link:
        aliases:
          - local.swagger.apisprout
    build:
      dockerfile: Dev.Dockerfile
    depends_on:
      - sonarqube-db
      - sonarqube
    environment:
      NODE_ENV: development
      HOST: '0.0.0.0'
      PORT: '3001'
      DB_CONFIG: |
        {
          "host": "host.docker.internal",
          "database": "pokemon",
          "username": "pokemon",
          "password": "pokemon",
          "port": 3307
        }
    ports:
      - 3001:3001
    command: >
      bash -c '
        npm run migrate:run
        npm run dev
      '

  pokemon-web:
    build:
      dockerfile: Dev.Dockerfile
    environment:
      NODE_ENV: development
      API_BASE_URL: 'http://localhost:3001/'
    ports:
      - '8080:8080'
      - '6006:6006'
    command: bash -c 'npm run storybook & npm run serve'

networks:
  swagger_link:
    external: true
