version: '3'

services:
  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: "swagger-editor"
    ports:
      - "8001:8080"

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8002:8080"
    volumes:
      - ../pokemon-api/swagger/openapi.yaml:/openapi.yaml
    environment:
      SWAGGER_JSON: /openapi.yaml
      # API_URL: ""

  swagger-nginx:
    image: nginx:mainline-alpine
    container_name: "swagger-nginx"
    depends_on:
      - pokemon-api
    ports:
      - "8003:8081"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      swagger_link:
        aliases:
          - local.swagger.api

  sonarqube-db:
    image: postgres:9.6
    container_name: 'sonarqube-db'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=sonar
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - /var/lib/postgresql/data

  sonarqube:
    image: sonarqube
    depends_on:
      - sonarqube-db
    container_name: 'sonarqube'
    ports:
      - "9000:9000"
    environment:
      - sonar.jdbc.url=jdbc:postgresql://sonarqube-db:5432/sonar
    volumes:
      - /opt/sonarqube/conf
      - /opt/sonarqube/data
      - /opt/sonarqube/extensions

  pokemon-db:
    image: postgres:9.6
    container_name: 'pokemon-db'
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=pokemon
      - POSTGRES_USER=pokemon
      - POSTGRES_PASSWORD=pokemon
    volumes:
      - /var/lib/postgresql/data

  pokemon-api:
    tty: true
    networks:
      swagger_link:
        aliases:
          - local.swagger.apisprout
    build:
      context: ../pokemon-api
      dockerfile: Dev.Dockerfile
    depends_on:
      - pokemon-db
      - sonarqube-db
      - sonarqube
    container_name: 'pokemon-api'
    volumes:
      - ../pokemon-api/:/usr/app/
      - /usr/app/node_modules
    environment:
      NODE_ENV: development
      HOST: '0.0.0.0'
      PORT: '3001'
      DB_CONFIG: |
        {
          "host": "host.docker.internal",
          "database": "pokemon",
          "username": "pokemon",
          "password": "pokemon",
          "port": "5433"
        }
    ports:
      - '3001:3001'
    entrypoint: './scripts/dev.sh'

  pokemon-client:
    tty: true
    build:
      context: ../pokemon-client
      dockerfile: Dev.Dockerfile
    volumes:
      - ../pokemon-client/:/usr/app/
      - /usr/app/node_modules
    environment:
      NODE_ENV: development
      API_BASE_URL: 'http://localhost:3001/'
    ports:
      - '8080:8080'
    entrypoint: ./scripts/dev.sh

networks:
  swagger_link:
    external: true
